DROP TABLE IF EXISTS DataStore;

CREATE TABLE DataStore(
Id INTEGER PRIMARY KEY,
Version INTEGER NOT NULL
);


DROP TABLE IF EXISTS Pods;

CREATE TABLE Pods(
Id INTEGER PRIMARY KEY,
Lot INTEGER,
Serial INTEGER,
RadioAddress INTEGER NOT NULL,
VersionPm TEXT,
VersionPi TEXT,
VersionUnknown TEXT,
	UNIQUE(Lot,Serial)
);

DROP TABLE IF EXISTS Commands;

CREATE TABLE Commands(
Id INTEGER PRIMARY KEY,
PodId INTEGER NOT NULL,
Date INTEGER NOT NULL,
Type INTEGER NOT NULL,
Json TEXT NOT NULL,
Status INTEGER NOT NULL,
	FOREIGN KEY(PodId) REFERENCES Pods(Id)
);

DROP TABLE IF EXISTS Statuses;

CREATE TABLE Statuses(
Id INTEGER PRIMARY KEY,
PodId INTEGER NOT NULL,
CommandId INTEGER NOT NULL,
Date INTEGER NOT NULL,
ActiveMinutes INTEGER NOT NULL,
Progress INTEGER NOT NULL,
BasalState INTEGER NOT NULL,
BolusState INTEGER NOT NULL,
AlertMask INTEGER NOT NULL,
InsulinReservoir REAL NOT NULL,
InsulinDelivered REAL NOT NULL,
InsulinNotDelivered REAL NOT NULL,
	FOREIGN KEY(PodId) REFERENCES Pods(Id),
	FOREIGN KEY(CommandId) REFERENCES Commands(Id)
);

DROP TABLE IF EXISTS AlertHistory;

CREATE TABLE AlertHistory(
Id INTEGER PRIMARY KEY,
PodId INTEGER NOT NULL,
CommandId INTEGER NOT NULL,
Date INTEGER NOT NULL,
Alert0 INTEGER NOT NULL,
Alert1 INTEGER NOT NULL,
Alert2 INTEGER NOT NULL,
Alert3 INTEGER NOT NULL,
Alert4 INTEGER NOT NULL,
Alert5 INTEGER NOT NULL,
Alert6 INTEGER NOT NULL,
Alert7 INTEGER NOT NULL,
	FOREIGN KEY(PodId) REFERENCES Pods(Id),
	FOREIGN KEY(CommandId) REFERENCES Commands(Id)
);

DROP TABLE IF EXISTS FaultHistory;

CREATE TABLE FaultHistory(
Id INTEGER PRIMARY KEY,
PodId INTEGER NOT NULL,
CommandId INTEGER NOT NULL,
Date INTEGER NOT NULL,
	FOREIGN KEY(PodId) REFERENCES Pods(Id),
	FOREIGN KEY(CommandId) REFERENCES Commands(Id)
);